apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: liable-goose-python 
  janus-idp.io/tekton: liable-goose-python
  backstage.io/kubernetes-id: liable-goose-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: liable-goose-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  